dcase_2019_task3_dataset:
  sr: 24000
  signals_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_dev_splitted
  train_annotations_path: /Users/ezajlerg/datasets/dcase_2019_task_3/train_annotations.csv
  validation_annotations_path: /Users/ezajlerg/datasets/dcase_2019_task_3/validation_annotations.csv
  test_annotations_path: /Users/ezajlerg/datasets/dcase_2019_task_3/validation_annotations.csv
  num_mics: 4
  sample_duration_in_seconds: 1