model:
  # NN Model settings
  pool_type: avg # max | avg
  pool_size: [1, 1]
  last_layer_dropout_rate: 0.0
  
  # Feature params
  n_input_channels: 4
  n_fft: 1024
  window: hann
  feature_type: stft # decoupled_stft (real and imag as separate channels) | stft (complex) | stft_magnitude

  output_type: scalar # scalar | frame
  target: azimuth_2d_point # model target: azimuth_in_radians | azimuth_complex_point | azimuth_2d_point | normalized_tdoa  
  loss: angular # angular | magnitude | angular_and_magnitude 

  conv_layers:
    - layer_1:
      type: complex_double # complex | real | complex_double | real_double
      n_channels: 64
      dropout_rate: 0.0
    - layer_2:
      type: complex_double
      n_channels: 64
      dropout_rate: 0.0
    - layer_3:
      type: complex_double
      n_channels: 64
      dropout_rate: 0.0
    - layer_4:
      type: complex_double
      n_channels: 64
      dropout_rate: 0.0
  init_conv_layers: False