model:
  # NN Model settings
  pool_type: avg # max | avg
  pool_size: [1, 2] # [1, 1] = No pooling | [1, 2] = Frequency pooling | [2, 2] = Time and frequency pooling
  last_layer_dropout_rate: 0.0
  activation: amp_tanh # tanh | relu | amp_tanh
  
  # Feature params
  n_input_channels: 4
  n_fft: 1024
  window: hann
  feature_type: cross_spectra # stft | cross_spectra

  output_type: scalar # scalar | frame
  target: azimuth_2d_point # model target: azimuth_in_radians | azimuth_complex_point | azimuth_2d_point | normalized_tdoa  
  loss: angular # angular | magnitude | angular_and_magnitude 

  conv_layers:
    - layer_1:
      type: complex_single # complex | real | complex_double | real_double
      n_channels: 64
      dropout_rate: 0.0
    - layer_2:
      type: real_single
      n_channels: 128
      dropout_rate: 0.0
    - layer_3:
      type: real_single
      n_channels: 256
      dropout_rate: 0.0
    - layer_4:
      type: real_single
      n_channels: 512
      dropout_rate: 0.0
  init_conv_layers: False