model:
  # NN Model settings
  pool_type: "avg" # "max" | "avg"
  pool_size: [2, 1]
  n_output_channels: 512
  n_conv_layers: 4
  conv_type: "depthwise_separable" # depthwise_separable | conv2d

  # Feature params
  n_fft: 1024
  n_mels: 64
  window: "hann"

  hop_length_in_seconds: 10e-3
  hop_length: 480 # int(hop_length_in_seconds * sr)

  feature_type: "stft" # decoupled_stft (real and imag as separate channels) | stft (complex) | stft_magnitude
