sr: 24000
train_wav_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_dev_splitted_multi
validation_wav_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_dev_splitted_multi
test_wav_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_eval_splitted_multi
train_csv_path: /Users/ezajlerg/datasets/dcase_2019_task_3/train_annotations_multi.csv
validation_csv_path: /Users/ezajlerg/datasets/dcase_2019_task_3/validation_annotations_multi.csv
test_csv_path: /Users/ezajlerg/datasets/dcase_2019_task_3/validation_annotations_multi.csv
test_wavs_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_eval_splitted_multi
num_mics: 4
sample_duration_in_seconds: 1
n_max_sources: 2
name: "dcase_2019_task3"