sr: 24000
train_wav_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_dev_multi_splitted
validation_wav_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_dev_multi_splitted
test_wav_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_eval_multi_splitted
train_csv_path: /Users/ezajlerg/datasets/dcase_2019_task_3/train_multi_annotations.csv
validation_csv_path: /Users/ezajlerg/datasets/dcase_2019_task_3/validation_multi_annotations.csv
test_csv_path: /Users/ezajlerg/datasets/dcase_2019_task_3/test_multi_annotations.csv
test_wavs_path: /Users/ezajlerg/datasets/dcase_2019_task_3/mic_eval_multi_splitted
num_mics: 4
sample_duration_in_seconds: 1
n_max_sources: 2