name: Test
on:
  pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          cd ${{ github.workspace }}
          pip install -r requirements.txt
          sudo apt-get install libsndfile1-dev
      - name: Run tests
        run: make test